### ISSUE TITLE
qpnp-charger.c: undeclared function (d803)

### ISSUE THREAD

**Issue by danielstuart14** [lg-devs/android_kernel_lge_msm8974#4]
When compiling to d803 (the only model that has qpnp-charger=y in config), I got that:

error: 'STS_CHE_STPCHG_TO_DECCUR' undeclared (first use in this function)
    if (res.change_lvl == STS_CHE_STPCHG_TO_DECCUR) {
                          ^

I saw that cm12.0 caf doesn't has STS_CHE_STPCHG_TO_DECCUR state. So I delete this state to compile, I'll test if charge still working (or even if it's booting).

**Comment by NotTsunami** [comment]
See below.

**Comment by Rashed97** [comment]
Not exactly. The d803 can't build this kernel because the defconfig hasn't been updated yet, but I'm working on it. The DTB might need some updates as well however.

**Comment by NotTsunami** [comment]
Whoops, sorry.

**Comment by danielstuart14** [comment]
Fixed!
Author: @Rashed97
Commit: ea691ac1a82151643a5b5f885dc95578707d6ff9
