### ISSUE TITLE
Bluetooth: btwrite: permission denied

### ISSUE THREAD

**Issue by danielstuart14** [lg-devs/android_kernel_lge_msm8974#7]
Hey. I think I found the sleep problem when BT is enabled.
 Here's what I get in logcat:
 upio_set : open(/proc/bluetooth/sleep/btwrite) for write failed: Permission denied (13)

So, I try change /proc/bluetooth/sleep/btwrite to RW (as it was OR), but it'd stayed giving me error. After this, I try to open btwrite, and then it showed me: unsupported to read.
 When all the other sleep archives (ex: btwake), gives me something. (ex: btwake:1)

**Comment by Rashed97** [comment]
If its a permission denied error that's either selinux or init, and I'm leaning more towards the latter. I'll take a look tonight.

**Comment by danielstuart14** [comment]
Fixed!
Author: @Drgravy 
Commit: https://github.com/lg-devs/android_device_lge_g2-common/commit/1d9df7f0598d25720ad7bffccd027c066c4e4b33
:D
